version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ../pgdata:/var/lib/postgresql/data
      - ../workspace:/home
    ports:
      - "5432:5432"
